export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
	"A quaint seaside cottage nestled among sand dunes, its weathered walls adorned with seashell garlands.",
	"A vibrant beach boardwalk bustling with people, lined with colorful shops selling souvenirs and seaside treats.",
	"A lazy summer afternoon spent drifting on a serene, sunlit lake aboard a charming wooden rowboat.",
	"A secluded, sun-dappled forest clearing, where wildflowers bloom and a gentle stream meanders through the greenery.",
	"A tropical paradise with crystal-clear waters, showcasing a breathtaking coral reef and a diverse array of marine life.",
	"A vintage-style ice cream truck parked by a sandy beach, offering frozen delights to happy beachgoers.",
	"An enchanting summer festival, filled with fairy lights, carnival rides, and an array of colorful market stalls.",
	"A picturesque vineyard bathed in golden sunlight, with rows of lush grapevines stretching towards the horizon.",
	"A sunlit wheat field, where a lone tree stands tall, casting a beautiful shadow on the golden waves.",
	"A serene lakeside cabin surrounded by towering evergreen trees, a peaceful escape into nature's embrace.",
	"A lively beach volleyball match with friends, with laughter and sandy toes in the warm, salty air.",
	"A classic convertible car driving along a coastal road, with the shimmering ocean on one side and palm trees on the other.",
	"An outdoor cinema under the stars, where people lounge on blankets, enjoying a movie beneath a balmy night sky.",
	"A charming farmer's market in full swing, offering an abundance of fresh fruits, vegetables, and artisanal crafts.",
	"A joyous summer campfire gathering, where friends share stories and toasted marshmallows in the fading light.",
	"A cluster of quaint beach huts adorned with colorful bunting, overlooking a vast expanse of sandy shoreline.",
	"A lively poolside party with inflatable flamingos, tropical cocktails, and friends basking in the summer vibes.",
	"A dreamy lavender field at sunset, with rows of fragrant purple blooms set against a painted sky.",
	"A picturesque, sunflower-filled meadow, buzzing with bees and butterflies on a sunny summer day.",
	"A rustic, wooden swing hanging from a sturdy tree branch, inviting anyone to feel the wind's embrace.",
	"A peaceful, sunlit garden patio adorned with climbing vines, perfect for enjoying a book and iced tea.",
	"A coastal cliffside with a breathtaking view of the vast ocean, where waves crash against the rocks below.",
	"A lively street fair with colorful tents, street performers, and a lively atmosphere of summer celebration.",
	"An idyllic countryside picnic spot, where a quaint, wooden picnic table awaits under the shade of an oak tree.",
	"A vibrant summer carnival, illuminated by the glowing lights of spinning rides and fun-filled games.",
	"A tropical waterfall hidden within lush foliage, its cool waters inviting visitors to take a refreshing dip.",
	"A picturesque, sunlit alley in a Mediterranean town, adorned with blooming flowers and rustic architecture.",
	"A group of friends playing beach volleyball on a sandy court with a view of the sparkling ocean.",
	"A charming summer cottage with a white picket fence, surrounded by a lush, well-tended garden.",
	"A mesmerizing starry night sky over a tranquil lake, reflecting the brilliance of the summer constellations.",
	"A tranquil summer sunset over the ocean, with hues of pink, orange, and gold gently reflecting off the calm waters.",
	"An inviting, sun-kissed field of wildflowers, alive with vibrant colors and buzzing with butterflies and bees.",
	"A rustic, beachside bonfire with friends, surrounded by twinkling fairy lights and the sound of waves crashing in the distance.",
	"A picturesque coastal town, where colorful beach umbrellas dot the sandy shoreline and sailboats glide across the azure sea.",
	"A delightful ice cream parlor, adorned with pastel-colored decor and an array of delicious, refreshing treats on display.",
	"A lush tropical oasis, featuring a cascading waterfall and palm trees providing shade to a serene emerald-green pool.",
	"A whimsical summer garden, with charming cottages covered in blooming vines, and a maze of fragrant flowers leading the way.",
];